### ISSUE TITLE
Missing preferences at startup

### ISSUE THREAD

**Issue by madmas** [ThomasDaheim/ownNoteEditor#2]
At startup, I get a NullPointerException:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at java.util.prefs.AbstractPreferences.put(AbstractPreferences.java:241)
	at tf.ownnote.ui.main.OwnNoteEditor.lambda$initEditor$3(OwnNoteEditor.java:293)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.scene.control.Labeled.setText(Labeled.java:145)
	at tf.ownnote.ui.main.OwnNoteEditor.setParameters(OwnNoteEditor.java:193)
	at tf.ownnote.ui.main.OwnNoteEditorManager.start(OwnNoteEditorManager.java:74)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

from what I got reading the code, it seems like some preferences are missing; how can I set them?

**Comment by ThomasDaheim** [comment]
Need to look into that. Might be an issue with access rights?

In the meantime, could you please try and use

'--ownCloudDir="C:\owncloudpath\Notes"'

to set your local ownNotes path?

**Comment by ThomasDaheim** [comment]
Have done an update in the logic on how to handle parameters from command line vs. preferences. Should hopefully really be a fix :-)

Now keep fingers crossed that i didn't mess up things in git...

**Comment by madmas** [comment]
Thank a lot, now I could run the application, looks good :+1: 
I openend PR #4  and #5 for small improvements :-)
